param(
  [string]$ImagesDir = "images",
  [string]$OutFile = "images/manifest.json",
  [string]$OutJsFile = "images/manifest.js"
)

$root = Get-Location
$imagesPath = Join-Path $root $ImagesDir

if (-not (Test-Path $imagesPath)) {
  throw "Images folder not found: $imagesPath"
}

$allowed = @(".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp", ".svg")

$files = Get-ChildItem -LiteralPath $imagesPath -File |
  Where-Object { $allowed -contains $_.Extension.ToLowerInvariant() } |
  Sort-Object Name |
  ForEach-Object { $_.Name }

$manifest = [ordered]@{
  files = $files
}

$outPath = Join-Path $root $OutFile
$outDir = Split-Path -Parent $outPath
if (-not (Test-Path $outDir)) {
  New-Item -ItemType Directory -Path $outDir | Out-Null
}

$manifest | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $outPath -Encoding UTF8
Write-Host "Wrote $($files.Count) file(s) to $OutFile"

$outJsPath = Join-Path $root $OutJsFile
$js = @(
  "// Auto-generated by generate-manifest.ps1",
  "// Used when opening index.html directly via file:// (no server).",
  "window.__IMAGE_MANIFEST_FILES__ = ",
  ($files | ConvertTo-Json -Depth 5),
  ";"
) -join "`n"

$js | Set-Content -LiteralPath $outJsPath -Encoding UTF8
Write-Host "Wrote $($files.Count) file(s) to $OutJsFile"