// Auto-generated by generate-manifest.ps1
// Used when opening index.html directly via file:// (no server).
window.__IMAGE_MANIFEST_FILES__ = 
[
    "sample_ (2).jpg",
    "sample_ (3).jpg",
    "sample_ (4).jpg",
    "sample_ (5).jpg",
    "sample_ (6).jpg"
]
;
